name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/more.png
    - assets/page-1/images/search-more.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/s1.png
    - assets/page-1/images/more-HX1.png
    - assets/page-1/images/chat-bubble.png
    - assets/page-1/images/ellipse-1.png
    - assets/page-1/images/slr-camera.png
    - assets/page-1/images/vector-MvK.png
    - assets/page-1/images/count.png
    - assets/page-1/images/ellipse-5-bg.png
    - assets/page-1/images/ellipse-1-Ud1.png
    - assets/page-1/images/avatar.png
    - assets/page-1/images/status.png
    - assets/page-1/images/search-more-sUP.png
    - assets/page-1/images/search-more-2Ao.png
    - assets/page-1/images/ellipse-6.png
    - assets/page-1/images/vector-7As.png
    - assets/page-1/images/people-skin-type-7.png
    - assets/page-1/images/vector-oK1.png
    - assets/page-1/images/ellipse-6-5bH.png
    - assets/page-1/images/rectangle-5.png
    - assets/page-1/images/ellipse-1-AKm.png
    - assets/page-1/images/count-xMR.png
    - assets/page-1/images/ellipse-3.png
    - assets/page-1/images/ellipse-3-oo1.png
    - assets/page-1/images/ellipse-4-bg.png
    - assets/page-1/images/ellipse-3-S5H.png
    - assets/page-1/images/ellipse-3-o7R.png
    - assets/page-1/images/ellipse-3-Efu.png
    - assets/page-1/images/s1-t3V.png
    - assets/page-1/images/people-skin-type-7-bCo.png
    - assets/page-1/images/ellipse-1-LAP.png
    - assets/page-1/images/slr-camera-UdH.png
    - assets/page-1/images/people-skin-type-8.png
    - assets/page-1/images/tabler-brand-meta.png
    - assets/page-1/images/ellipse-6-GT5.png
    - assets/page-1/images/count-Ba3.png
    - assets/page-1/images/s1-mFR.png
    - assets/page-1/images/ellipse-6-HzT.png
    - assets/page-1/images/vector-e4K.png
    - assets/page-1/images/vector-6hR.png
    - assets/page-1/images/vector-PXR.png
    - assets/page-1/images/people-skin-type-7-bKy.png
    - assets/page-1/images/s1-JEP.png
    - assets/page-1/images/line-2.png
    - assets/page-1/images/ellipse-3-vRR.png
    - assets/page-1/images/default.png
    - assets/page-1/images/status-uHM.png
    - assets/page-1/images/vector-2My.png
    - assets/page-1/images/ellipse-3-9Sb.png
    - assets/page-1/images/vector-5b9.png
    - assets/page-1/images/ellipse-1-1Uo.png
    - assets/page-1/images/vector-U7V.png
    - assets/page-1/images/count-inX.png
    - assets/page-1/images/s1-TEK.png
    - assets/page-1/images/ellipse-1-NMH.png
    - assets/page-1/images/ellipse-1-tqR.png
    - assets/page-1/images/ellipse-3-oxP.png
    - assets/page-1/images/status-LhR.png
    - assets/page-1/images/icon-chevron-right.png
    - assets/page-1/images/status-kWF.png
    - assets/page-1/images/vector-sqm.png
    - assets/page-1/images/vector-ozK.png
    - assets/page-1/images/vector-LzF.png
    - assets/page-1/images/s1-5S3.png
    - assets/page-1/images/vector-1ab.png
    - assets/page-1/images/line-2-66F.png
    - assets/page-1/images/ellipse-1-2Eo.png
    - assets/page-1/images/ellipse-6-juu.png
    - assets/page-1/images/ellipse-1-foZ.png
    - assets/page-1/images/ellipse-3-zaw.png
    - assets/page-1/images/vector-imq.png
    - assets/page-1/images/ellipse-1-rNF.png
    - assets/page-1/images/ellipse-6-mVD.png
    - assets/page-1/images/slr-camera-e3D.png
    - assets/page-1/images/ellipse-6-bg.png
    - assets/page-1/images/ellipse-6-vkj.png
    - assets/page-1/images/vector-46F.png
    - assets/page-1/images/vector-P8X.png
    - assets/page-1/images/vector-7aK.png
    - assets/page-1/images/ellipse-6-3D5.png
    - assets/page-1/images/icon-chevron-right-WMZ.png
    - assets/page-1/images/ellipse-1-SFD.png
    - assets/page-1/images/rectangle-5-Zaj.png
    - assets/page-1/images/s1-YB5.png
    - assets/page-1/images/ellipse-1-G75.png
    - assets/page-1/images/more-zYs.png
    - assets/page-1/images/line-2-XHu.png
    - assets/page-1/images/vector-r5H.png
    - assets/page-1/images/auto-group-lwwj.png
    - assets/page-1/images/vector-GPu.png
    - assets/page-1/images/vector-QFD.png
    - assets/page-1/images/vector-L8s.png
    - assets/page-1/images/ellipse-3-fS3.png
    - assets/page-1/images/s1-Q8j.png
    - assets/page-1/images/ellipse-1-vsm.png
    - assets/page-1/images/material-symbols-phone-callback.png
    - assets/page-1/images/ellipse-4-bg-TmD.png
    - assets/page-1/images/s1-Pum.png
    - assets/page-1/images/ellipse-6-ix3.png
    - assets/page-1/images/ellipse-4-bg-St3.png
    - assets/page-1/images/ellipse-6-nBD.png
    - assets/page-1/images/ellipse-1-eaF.png
    - assets/page-1/images/s1-ktB.png
    - assets/page-1/images/ellipse-1-BTh.png
    - assets/page-1/images/logos-whatsapp-icon.png
    - assets/page-1/images/vector-MX1.png
    - assets/page-1/images/auto-group-jbjb.png
    - assets/page-1/images/ellipse-1-nbD.png
    - assets/page-1/images/more-Rbh.png
    - assets/page-1/images/ellipse-8-bg.png
    - assets/page-1/images/ellipse-8-bg-ZW3.png
    - assets/page-1/images/ellipse-8-bg-6fD.png
    - assets/icons/images/vector-yHm.png
    - assets/page-1/images/slr-camera-AyH.png
    - assets/page-1/images/ellipse-8-bg-P9D.png
    - assets/icons/images/avatar-8tK.png
    - assets/page-1/images/people-skin-type-7-wpf.png
    - assets/page-1/images/ellipse-4-bg-Ckb.png
    - assets/page-1/images/ellipse-4-bg-7ZV.png
    - assets/page-1/images/ellipse-8-bg-1DM.png
    - assets/page-1/images/search-more-N9Z.png
    - assets/page-1/images/ellipse-8-bg-3bZ.png
    - assets/page-1/images/ellipse-8-bg-VRV.png
    - assets/page-1/images/ellipse-8-bg-QHZ.png
    - assets/icons/images/icon-user.png
    - assets/icons/images/people-skin-type-7-MT9.png
    - assets/icons/images/more-vdy.png
    - assets/icons/images/chat-bubble-JPD.png
    - assets/icons/images/slr-camera-QYb.png
    - assets/page-1/images/ellipse-8-bg-gsM.png
    - assets/icons/images/search-more-sqM.png
    - assets/page-1/images/ellipse-6-bg-AWw.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
